name: PR Linters and Test
on:
  push:
    branches:
      - 'git_hooks_marcos'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Instalar dependencias
        working-directory: front
        run: npm ci
      - name: Pasar prettier
        working-directory: front
        run: npm run prettier
      - name: Pasar test
        working-directory: front
        run: CI=True npm run test
      - name: Generar build
        working-directory: front
        run: npm run build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//039QQDhle1FA5CgYIARAAGAMSNwF-L9IrbwhRxSGjB1I9pZ3NBrwQ_TIoVZ6KfF4EwuB8E-aA00U6ZgaB7YB4QvzdO_tRWenkbcA